"""empty message

Revision ID: 042fab3ba52a
Revises: 69ff21f1e14a
Create Date: 2016-02-22 00:54:21.462862

"""

# revision identifiers, used by Alembic.
revision = '042fab3ba52a'
down_revision = '69ff21f1e14a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('is_retweet', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'is_retweet')
    ### end Alembic commands ###
