"""empty message

Revision ID: 1f4aa62844c9
Revises: 26dead7d666e
Create Date: 2016-02-20 17:18:14.178357

"""

# revision identifiers, used by Alembic.
revision = '1f4aa62844c9'
down_revision = '26dead7d666e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('twitter_follower_id', sa.BigInteger(), nullable=True))
    op.add_column('followers', sa.Column('twitter_id', sa.BigInteger(), nullable=True))
    op.drop_column('followers', 'follower_id')
    op.alter_column('users', 'twitter_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'twitter_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('followers', sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('followers', 'twitter_id')
    op.drop_column('followers', 'twitter_follower_id')
    ### end Alembic commands ###
