"""empty message

Revision ID: 26dead7d666e
Revises: 7ff8be557ae7
Create Date: 2016-02-20 14:29:59.702089

"""

# revision identifiers, used by Alembic.
revision = '26dead7d666e'
down_revision = '7ff8be557ae7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('follower_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followers', 'follower_id')
    ### end Alembic commands ###
