"""empty message

Revision ID: 69ff21f1e14a
Revises: 1251ef11791b
Create Date: 2016-02-21 22:38:56.002053

"""

# revision identifiers, used by Alembic.
revision = '69ff21f1e14a'
down_revision = '1251ef11791b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tweet_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('text', sa.String(length=250), nullable=True),
    sa.Column('source', sa.String(length=250), nullable=True),
    sa.Column('in_reply_to_status_id', sa.BigInteger(), nullable=True),
    sa.Column('in_reply_to_user_id', sa.BigInteger(), nullable=True),
    sa.Column('in_reply_to_screen_name', sa.String(length=250), nullable=True),
    sa.Column('is_quote_status', sa.Boolean(), nullable=True),
    sa.Column('retweet_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tweet_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweets')
    ### end Alembic commands ###
