"""empty message

Revision ID: 7ff8be557ae7
Revises: 56c9b0fcb614
Create Date: 2016-02-20 14:26:47.569379

"""

# revision identifiers, used by Alembic.
revision = '7ff8be557ae7'
down_revision = '56c9b0fcb614'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followers', 'follower_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
