"""empty message

Revision ID: 8301b7d32db8
Revises: 33c2e51098d7
Create Date: 2016-02-19 19:50:37.178699

"""

# revision identifiers, used by Alembic.
revision = '8301b7d32db8'
down_revision = '33c2e51098d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twitter_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['twitter_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'twitter_id')
    ### end Alembic commands ###
